__python_base: &python_base
  language: python
  python:
    - '3.8'
  before_install:
    - python -m pip install --upgrade pip wheel
    - pip install -r requirements.dev.txt


stages:
  - lint
  - test
  - deploy


matrix:
  include:

    # LINT

    - name: 'flake8'
      stage: lint
      <<: *python_base
      script:
        - flake8

    - name: 'mypy'
      stage: lint
      <<: *python_base
      script:
        - mypy $(find -name "*.py" -not -path "./venv/*" -not -path "./**/migrations/*.py")

    - name: 'isort'
      stage: lint
      <<: *python_base
      script:
        - isort --check .

    # TEST

    - name: 'tests'
      stage: test
      <<: *python_base
      script:
        - python manage.py test  --settings=settings.ci

    - name: 'django checks'
      stage: test
      <<: *python_base
      script:
        - python manage.py makemigrations --check --settings=settings.ci
        - python manage.py migrate --settings=settings.ci
        - python manage.py check --settings=settings.ci

env:
  - DST_TOKEN="DST_TOKEN"
