# Generated by Django 3.1.8 on 2021-07-04 14:49

import django.db.models.deletion
from django.db import migrations, models


def create_profiles(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    User = apps.get_model('auth', 'User')
    profiles = []
    users = []
    for user in User.objects.all():
        users.append(user.username)
        profiles.append(Profile(user=user))
    Profile.objects.bulk_create(profiles)
    print('\nProfiles were created for users:', ', '.join(users))


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('discord_id', models.TextField(null=True, unique=True)),
            ],
            options={
                'verbose_name': "User's profile",
                'verbose_name_plural': 'Users profile',
            },
        ),
        migrations.RunPython(create_profiles)
    ]
