# Generated by Django 3.1.8 on 2021-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverbuild',
            old_name='status',
            new_name='success',
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serverbuild',
            name='kind',
            field=models.CharField(choices=[('BUILD', 'Build'), ('RUN', 'Run')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Just created'), ('BUILT', 'Server ready to start'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped')], default='CREATED', max_length=32),
        ),
    ]
