# Generated by Django 3.1.8 on 2021-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_update_server_add_mod_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
