# noqa: E501
from servers.helpers.configurator.base import BaseConfigurator
from servers.helpers.configurator.fields import (BooleanField, NumberField,
                                                 TextField)


class MinecraftConfigurator(BaseConfigurator):
    fields = {
        'spawn-protection': NumberField(
            name='spawn-protection',
            description='',
            required=True,
            default=16,
            editable=True,
            min_value=1,
            max_value=100,
        ),
        'max-tick-time': NumberField(
            name='max-tick-time',
            description='',
            required=True,
            default=-1,
            editable=False,
            min_value=-1,
            max_value=2 ^ 63 - 1,
        ),
        'query.port': NumberField(
            name='query.port',
            description='',
            required=True,
            default=25565,
            editable=False,
            min_value=1,
            max_value=65535,
        ),
        'generator-settings': TextField(
            name='generator-settings',
            description='',
            required=False,
            default=None,
            editable=False,
        ),
        'sync-chunk-writes': BooleanField(
            name='sync-chunk-writes',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'force-gamemode': BooleanField(
            name='force-gamemode',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'allow-nether': BooleanField(
            name='allow-nether',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'enforce-whitelist': BooleanField(
            name='enforce-whitelist',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'gamemode': TextField(
            name='gamemode',
            description='',
            required=True,
            default='survival',
            editable=True,
            choices=[
                'survival',
                'creative',
                'adventure',
                'spectator',
            ]
        ),
        'broadcast-console-to-ops': BooleanField(
            name='broadcast-console-to-ops',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'enable-query': BooleanField(
            name='enable-query',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'player-idle-timeout': NumberField(
            name='player-idle-timeout',
            description='',
            required=True,
            default=0,
            editable=True,
            min_value=0,
        ),
        'difficulty': TextField(
            name='difficulty',
            description='',
            required=True,
            default='easy',
            editable=True,
            choices=[
                'peaceful',
                'easy',
                'normal',
                'hard',
            ],
        ),
        'broadcast-rcon-to-ops': BooleanField(
            name='broadcast-rcon-to-ops',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'spawn-monsters': BooleanField(
            name='spawn-monsters',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'op-permission-level': NumberField(
            name='op-permission-level',
            description='',
            required=True,
            default=4,
            editable=True,
            min_value=1,
            max_value=4,
        ),
        'pvp': BooleanField(
            name='pvp',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'snooper-enabled': BooleanField(
            name='snooper-enabled',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'level-type': TextField(
            name='level-type',
            description='',
            required=True,
            default='default',
            editable=True,
            choices=[
                'default',
                'flat',
                'largebiomes',
                'amplified',
            ],
        ),
        'hardcore': BooleanField(
            name='hardcore',
            description='',
            required=True,
            default=False,
            editable=True,
        ),
        'enable-command-block': BooleanField(
            name='enable-command-block',
            description='',
            required=True,
            default=False,
            editable=True,
        ),
        'network-compression-threshold': NumberField(
            name='network-compression-threshold',
            description='',
            required=True,
            default=256,
            editable=False,
        ),
        'max-players': NumberField(
            name='max-players',
            description='',
            required=True,
            default=3,
            editable=True,
            min_value=1,
            max_value=5,
        ),
        'max-world-size': NumberField(
            name='max-world-size',
            description='',
            required=True,
            default=15000,
            editable=True,
            min_value=1,
            max_value=15000,
        ),
        'resource-pack-sha1': TextField(
            name='resource-pack-sha1',
            description='',
            required=False,
            default='',
            editable=False,
        ),
        'function-permission-level': NumberField(
            name='function-permission-level',
            description='',
            required=True,
            default=2,
            editable=False,
            min_value=1,
            max_value=4,
        ),
        'rcon.port': NumberField(
            name='rcon.port',
            description='',
            required=True,
            default=25575,
            editable=False,
            min_value=1,
            max_value=65535,
        ),
        'server-port': NumberField(
            name='server-port',
            description='',
            required=True,
            default=25565,
            editable=False,
            min_value=1,
            max_value=65535,
        ),
        'server-ip': TextField(
            name='server-ip',
            description='',
            required=False,
            default='',
            editable=False,
        ),
        'spawn-npcs': BooleanField(
            name='spawn-npcs',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'allow-flight': BooleanField(
            name='allow-flight',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'level-name': TextField(
            name='level-name',
            description='',
            required=True,
            default='world',
            editable=False,
        ),
        'view-distance': NumberField(
            name='view-distance',
            description='',
            required=True,
            default=10,
            editable=False,
            min_value=3,
            max_value=15,
        ),
        'resource-pack': TextField(
            name='resource-pack',
            description='',
            required=False,
            default='',
            editable=False,
        ),
        'spawn-animals': BooleanField(
            name='spawn-animals',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'white-list': BooleanField(
            name='white-list',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'rcon.password': TextField(
            name='rcon.password',
            description='',
            required=True,
            default='verySecretPassword',
            editable=False,
        ),
        'generate-structures': BooleanField(
            name='generate-structures',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'online-mode': BooleanField(
            name='online-mode',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'max-build-height': NumberField(
            name='max-build-height',
            description='',
            required=True,
            default=256,
            editable=False,
            min_value=64,
            max_value=256,
        ),
        'level-seed': NumberField(
            name='level-seed',
            description='',
            required=False,
            default=None,
            editable=True,
        ),
        'prevent-proxy-connections': BooleanField(
            name='prevent-proxy-connections',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'use-native-transport': BooleanField(
            name='use-native-transport',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'motd': TextField(
            name='motd',
            description='',
            required=True,
            default='Donkey Engine server',
            editable=True,
        ),
        'enable-rcon': BooleanField(
            name='enable-rcon',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
    }
