from servers.helpers.configurator.base import BaseConfigurator
from servers.helpers.configurator.fields import BooleanField, TextField, NumberField


class MinecraftConfigurator(BaseConfigurator):
    fields = {
        'spawn-protection': NumberField(
            name='spawn-protection',
            description='Радиус защиты территории спауна в блоках (эту территорию смогут изменять только операторы). Радиус 0 дает защиту единственного блока, 1 — зоны 3×3 и так далее. Эта опция не генерируется при первой загрузке, а появляется, когда первый игрок заходит на сервер. После 1.4.2 защита спауна автоматически отключается, если у сервера нет ни одного оператора.',
            required=True,
            default=16,
            editable=False,
            min_value=1,
            max_value=100,
        ),
        'max-tick-time': NumberField(
            name='max-tick-time',
            description='Максимальное количество миллисекунд, которое может занять один тик, прежде чем серверный сторожевой таймер останавливает сервер с сообщением. Один тик сервера занял 60,00 секунд (должно быть не более 0,05 сек); Считая, что он потерпел крах, сервер принудительно завершит работу. Как только этот критерий удовлетворен, он вызывает System.exit (1). -1 - полностью отключить сторожевой таймер (эта опция была добавлена в 14w32a)',
            required=True,
            default=-1,
            editable=False,
            min_value=-1,
            max_value=2^63 - 1,
        ),
        'query.port': NumberField(
            name='query.port',
            description='Порт для получения информации о сервере. Появляется автоматически при enable-query=true.',
            required=True,
            default=25565,
            editable=False,
            min_value=1,
            max_value=65535,
        ),
        'generator-settings': TextField(
            name='generator-settings',
            description='Эта строка задает шаблон генерации суперплоского мира.',
            required=False,
            default=None,
            editable=False,
        ),
        'sync-chunk-writes': BooleanField(
            name='sync-chunk-writes',
            description='Включает синхронную запись чанков.',
            required=True,
            default=True,
            editable=False,
        ),
        'force-gamemode': BooleanField(
            name='force-gamemode',
            description='Если true, то при подключении к серверу режим игры игрока изменятся на стандартный, указанный в gamemode.',
            required=True,
            default=False,
            editable=False,
        ),
        'allow-nether': BooleanField(
            name='allow-nether',
            description='Данный параметр определяет возможность перехода в Нижний мир. Если отключить, все игроки, находившиеся в Нижнем мире, будут перемещены в обычный. Не влияет на переход в Край.',
            required=True,
            default=True,
            editable=False,
        ),
        'enforce-whitelist': BooleanField(
            name='enforce-whitelist',
            description='Позволяет включать/отключать перезагрузку вайтлиста при заходе игрока, прежде чем отключить его от сервера.',
            required=True,
            default=False,
            editable=False,
        ),
        'gamemode': TextField(
            name='gamemode',
            description='Стандартный игровой режим, автоматически устанавливаемый всем впервые зашедшим на сервер игрокам. Режим отдельного игрока меняется командой /gamemode.',
            required=True,
            default='survival',
            editable=True,
            choices=[
                'survival',
                'creative',
                'adventure',
                'spectator',
            ]
        ),
        'broadcast-console-to-ops': BooleanField(
            name='broadcast-console-to-ops',
            description='Позволяет вывести результат выполнения команды в консоли всем операторам сервера.',
            required=True,
            default=True,
            editable=False,
        ),
        'enable-query': BooleanField(
            name='enable-query',
            description='Позволяет активировать протокол GameSpy4 для прослушки сервера (получении информации о сервере).',
            required=True,
            default=False,
            editable=False,
        ),
        'player-idle-timeout': NumberField(
            name='player-idle-timeout',
            description='Если не поставлен ноль, то игроки будут автоматически отключаться от сервера, если они ничего не делали в течение указанного времени (в минутах).',
            required=True,
            default=0,
            editable=True,
            min_value=0,
        ),
        'difficulty': TextField(
            name='difficulty',
            description='Уровень сложности.',
            required=True,
            default='easy',
            editable=True,
            choices=[
                'peaceful',
                'easy',
                'normal',
                'hard',
            ],
        ),
        'broadcast-rcon-to-ops': BooleanField(
            name='broadcast-rcon-to-ops',
            description='Позволяет вывести результат выполнения команды в консоли RCON всем операторам сервера.',
            required=True,
            default=True,
            editable=False,
        ),
        'spawn-monsters': BooleanField(
            name='spawn-monsters',
            description='Если значение параметра true, то, как и в одиночной игре, в ночное время и в тёмных пещерах на карте будут появляться враждебные мобы и будут стараться нанести вред игрокам на сервере. Если значение false, враждебные мобы (например, скелеты, зомби) не будут автоматически появляться во время игры, однако их можно заспаунить с помощью яиц призывания. Все находившиеся на карте мобы останутся.',
            required=True,
            default=True,
            editable=True,
        ),
        'op-permission-level': NumberField(
            name='op-permission-level',
            description='Позволяет изменять права операторов.',
            required=True,
            default=4,
            editable=True,
            min_value=1,
            max_value=4,
        ),
        'pvp': BooleanField(
            name='pvp',
            description='Включает/отключает получение урона игрокам от атак других игроков на сервере. При true игроки смогут «воевать» между собой, убивая друг друга. Если уставлено значение false, игроки не смогут наносить прямой урон один другому.',
            required=True,
            default=True,
            editable=True,
        ),
        'snooper-enabled': BooleanField(
            name='snooper-enabled',
            description='Разрешает серверу отправлять некоторую статистику и данные разработчикам.',
            required=True,
            default=False,
            editable=False,
        ),
        'level-type': TextField(
            name='level-type',
            description='Определяет тип мира.',
            required=True,
            default='default',
            editable=True,
            choices=[
                'default',
                'flat',
                'largebiomes',
                'amplified',
            ],
        ),
        # 'hardcore': 'false',
        # 'enable-command-block': 'false',
        # 'network-compression-threshold': '256',
        # 'max-players': '20',
        # 'max-world-size': '29999984',
        # 'resource-pack-sha1': '',
        # 'function-permission-level': '2',
        # 'rcon.port': '25575',
        # 'server-port': '25565',
        # 'server-ip': '',
        # 'spawn-npcs': 'true',
        # 'allow-flight': 'false',
        # 'level-name': 'world',
        # 'view-distance': '10',
        # 'resource-pack': '',
        # 'spawn-animals': 'true',
        # 'white-list': 'false',
        # 'rcon.password': '',
        # 'generate-structures': 'true',
        # 'online-mode': 'true',
        # 'max-build-height': '256',
        # 'level-seed': '',
        # 'prevent-proxy-connections': 'false',
        # 'use-native-transport': 'true',
        # 'motd': 'A Minecraft Server',
        # 'enable-rcon': 'false',
    }
