# noqa: E501
from servers.helpers.configurator.base import BaseConfigurator
from servers.helpers.configurator.fields import BooleanField, TextField, NumberField


class MinecraftConfigurator(BaseConfigurator):
    fields = {
        'spawn-protection': NumberField(
            name='spawn-protection',
            description='',
            required=True,
            default=16,
            editable=True,
            min_value=1,
            max_value=100,
        ),
        'max-tick-time': NumberField(
            name='max-tick-time',
            description='',
            required=True,
            default=-1,
            editable=False,
            min_value=-1,
            max_value=2 ^ 63 - 1,
        ),
        'query.port': NumberField(
            name='query.port',
            description='',
            required=True,
            default=25565,
            editable=False,
            min_value=1,
            max_value=65535,
        ),
        'generator-settings': TextField(
            name='generator-settings',
            description='',
            required=False,
            default=None,
            editable=False,
        ),
        'sync-chunk-writes': BooleanField(
            name='sync-chunk-writes',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'force-gamemode': BooleanField(
            name='force-gamemode',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'allow-nether': BooleanField(
            name='allow-nether',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'enforce-whitelist': BooleanField(
            name='enforce-whitelist',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'gamemode': TextField(
            name='gamemode',
            description='',
            required=True,
            default='survival',
            editable=True,
            choices=[
                'survival',
                'creative',
                'adventure',
                'spectator',
            ]
        ),
        'broadcast-console-to-ops': BooleanField(
            name='broadcast-console-to-ops',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'enable-query': BooleanField(
            name='enable-query',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'player-idle-timeout': NumberField(
            name='player-idle-timeout',
            description='',
            required=True,
            default=0,
            editable=True,
            min_value=0,
        ),
        'difficulty': TextField(
            name='difficulty',
            description='',
            required=True,
            default='easy',
            editable=True,
            choices=[
                'peaceful',
                'easy',
                'normal',
                'hard',
            ],
        ),
        'broadcast-rcon-to-ops': BooleanField(
            name='broadcast-rcon-to-ops',
            description='',
            required=True,
            default=True,
            editable=False,
        ),
        'spawn-monsters': BooleanField(
            name='spawn-monsters',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'op-permission-level': NumberField(
            name='op-permission-level',
            description='',
            required=True,
            default=4,
            editable=True,
            min_value=1,
            max_value=4,
        ),
        'pvp': BooleanField(
            name='pvp',
            description='',
            required=True,
            default=True,
            editable=True,
        ),
        'snooper-enabled': BooleanField(
            name='snooper-enabled',
            description='',
            required=True,
            default=False,
            editable=False,
        ),
        'level-type': TextField(
            name='level-type',
            description='',
            required=True,
            default='default',
            editable=True,
            choices=[
                'default',
                'flat',
                'largebiomes',
                'amplified',
            ],
        ),
        # 'hardcore': 'false',
        # 'enable-command-block': 'false',
        # 'network-compression-threshold': '256',
        # 'max-players': '20',
        # 'max-world-size': '29999984',
        # 'resource-pack-sha1': '',
        # 'function-permission-level': '2',
        # 'rcon.port': '25575',
        # 'server-port': '25565',
        # 'server-ip': '',
        # 'spawn-npcs': 'true',
        # 'allow-flight': 'false',
        # 'level-name': 'world',
        # 'view-distance': '10',
        # 'resource-pack': '',
        # 'spawn-animals': 'true',
        # 'white-list': 'false',
        # 'rcon.password': '',
        # 'generate-structures': 'true',
        # 'online-mode': 'true',
        # 'max-build-height': '256',
        # 'level-seed': '',
        # 'prevent-proxy-connections': 'false',
        # 'use-native-transport': 'true',
        # 'motd': 'A Minecraft Server',
        # 'enable-rcon': 'false',
    }
