# Generated by Django 3.1.6 on 2021-04-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('filepath', models.FileField(max_length=512, upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ('version',),
                'unique_together': {('version', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name': 'Mod',
                'verbose_name_plural': 'Mods',
                'ordering': ('name',),
                'unique_together': {('name', 'game')},
            },
        ),
        migrations.CreateModel(
            name='ModVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(max_length=512, upload_to='')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.mod')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameversion')),
            ],
            options={
                'verbose_name': 'Mod version',
                'verbose_name_plural': 'Mod versions',
                'unique_together': {('version', 'mod')},
            },
        ),
    ]
