# Generated by Django 3.1.8 on 2021-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='build_key',
            field=models.CharField(default='Minecraft: Java Edition', max_length=32),
        ),
    ]
