# Generated by Django 3.1.8 on 2021-05-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_add_mod_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='versions',
            field=models.ManyToManyField(related_name='mods', to='games.GameVersion'),
        ),
    ]
