# Generated by Django 3.1.6 on 2021-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mods',
            name='version',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
