# Generated by Django 3.1.6 on 2021-02-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_mods_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mods',
            name='game',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='version',
        ),
    ]
