# Generated by Django 3.1.8 on 2021-06-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_add_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='versions',
        ),
        migrations.CreateModel(
            name='ModVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('filepath', models.FileField(max_length=512, upload_to='')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.mod')),
                ('versions', models.ManyToManyField(related_name='mods', to='games.GameVersion')),
            ],
            options={
                'verbose_name': 'Mod version',
                'verbose_name_plural': 'Mod versions',
                'ordering': ('mod', 'name'),
                'unique_together': {('name', 'mod')},
            },
        ),
    ]
