# Generated by Django 3.1.8 on 2021-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_mod_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mod',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
