# Generated by Django 3.1.6 on 2021-02-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_mods_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='mods',
            name='verion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.mods'),
            preserve_default=False,
        ),
    ]
