# Generated by Django 3.1.6 on 2021-02-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_mods_verion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mods',
            old_name='verion',
            new_name='version',
        ),
    ]
