# Generated by Django 3.1.6 on 2021-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210215_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mods',
            name='version',
        ),
    ]
