# Generated by Django 3.1.6 on 2021-02-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_mods_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mods',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.version'),
            preserve_default=False,
        ),
    ]
