name: Deploy commit

on: workflow_dispatch

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - name: 'Get version'
      id: releasetag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1.0
    - name: Release pushed commit
      run: |
        curl \
        -X POST \
        -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/donkey-engine/deploy/actions/workflows/deploy_commit.yml/dispatches \
        -d '{"ref": "master", "inputs": {"commit": "${GITHUB_SHA}", "branch": "${GITHUB_REF##*/}", "repo": "django", "release": "${{ steps.releasetag.outputs.tag }}"}}'
