name: Deploy release

on:
  release:
    types: [published]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Release pushed commit
      run: |
        curl \
        -X POST \
        -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/donkey-engine/deploy/actions/workflows/deploy_release.yml/dispatches \
        -d '{"ref": "master", "inputs": {"repo": "django", "release": "${{ github.event.release.tag_name }}"}}'
